application:
    username: admin@phptravels.com
    password: demoadmin
    
webdriver:
    sauce:
        username:
        key:
        browserName:
        caps:
            browserName: chrome 
            version: 66.0
            platform: macOS 10.13
    remote:
        url: http://172.26.21.92:4444/wd/hub
        platform: Windows
    # Available types: remote, local
    type: remote
    chrome:
        driver: C:\chromedriver.exe
        arguments: ["--disable-extensions", "--headless"]
    firefox:
        driver: C:\geckodriver.exe
        preferences:
            browser.download.dir: H:\Downloads
            browser.download.manager.showWhenStarting: False
    wait:
        short: 10
        long: 30
    implicit_wait: 10
tests:
	mobile:
	    scope: class
	    no_reset: False
	    full_reset: False
    browser:
        # chrome, firefox if local
        name: firefox
        scope: class
mobile:
    android:
        browserName: 
        deviceName: 
        platformName:
        app:
        orientation:
        platformVersion: 
        appActivity:
        
        
        
api:
    request:
        timeout: 20