application:
    username: admin@phptravels.com
    password: demoadmin
    
webdriver:
    sauce:
        username:
        key:
        browserName:
        caps:
            browserName: chrome 
            version: 66.0
            platform: macOS 10.13

    remote:
        url: 
        platform: 
    
    # Available types: remote, local
    type: local
    
    chrome:
        driver: C:\chromedriver.exe
        arguments: ["--disable-extensions"]
    
    firefox:
        driver: path
        preferences:
            browser.download.dir: H:\Downloads
            browser.download.manager.showWhenStarting: False
    wait:
        short: 10
        long: 30
    implicit_wait: 10
        
tests:
    browser:
        # chrome, firefox if local
        name: chrome
        scope: class
        
api:
    request:
        timeout: 20