application:
    username: mrane
    password: password
    
webdriver:
    chrome:
        driver: C:\chromedriver.exe
        arguments: ["--disable-extensions", "--headless"]
    firefox:
        driver: path
        preferences:
            browser.download.dir: H:\Downloads
            browser.download.manager.showWhenStarting: False
    wait:
        short: 10
        long: 30
    
        
tests:
    browser: chrome