application:
    username: admin@phptravels.com
    password: demoadmin
webdriver:
    sauce:
        username: null
        key: null
        browserName: null
        caps:
            browserName: chrome
            version: 66
            platform: 'macOS 10.13'
    remote:
        url: 'http://172.26.21.92:4444/wd/hub'
        platform: Windows
    type: remote
    chrome:
        driver: 'C:\chromedriver.exe'
        arguments:
            - '--disable-extensions'
            - '--headless'
    firefox:
        driver: 'C:\geckodriver.exe'
        preferences:
            browser.download.dir: 'H:\Downloads'
            browser.download.manager.showWhenStarting: false
    wait:
        short: 10
        long: 30
    implicit_wait: 10
tests:
    mobile:
        scope: class
        no_reset: false
        full_reset: false
    browser:
        name: firefox
        scope: class
mobile:
    remote:
        url: null
    capabilities:
        browserName: null
        deviceName: null
        platformName: null
        app: null
        orientation: null
        platformVersion: null
        appActivity: null
api:
    request:
        timeout: 20
