application:
    username: admin@phptravels.com
    password: demoadmin
    
webdriver:
    chrome:
        driver: C:\chromedriver.exe
        arguments: ["--disable-extensions", "--headless"]
    firefox:
        driver: path
        preferences:
            browser.download.dir: H:\Downloads
            browser.download.manager.showWhenStarting: False
    wait:
        short: 10
        long: 30
    implicit_wait: 10
        
tests:
    browser: chrome

reporting: html

api:
    request:
        timeout: 20